### ISSUE TITLE
Specify Format Optional CLA

### ISSUE THREAD

**Issue by hcars** [NSSAC/graph-plot#10]
Add an optional CLA that if specified should be one of: 
		* lgl
		* adjacency
		* dimacs
		* dl
		* edgelist, edges, edge
		* graphviz, dot
		* gml
		* graphml
		* graphmlz
		* leda
		* ncol
		* pajek, net
		* pickle
This will determine what format igraph interprets the input file as if the CLA is specify. It can be defaulted to None and ignored if this function is not needed.

**Comment by cckuhlman** [comment]
I do not understand this.  Should it not be the case that any code that takes a graph as input needs also the graph format as a CLA?

**Comment by hcars** [comment]
igraph will automatically use the file extension to do this. That is what we are doing right now. This will offer more flexibility, so it doesn't have to work off the file extension.
