### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by hcars** [NSSAC/graph-plot#14]
@cckuhlman @ssravi-1984
We used this [document](https://docs.google.com/document/d/14pRrsp85WMO6vPdqySi_USkaBvbBVvqCyS3u-1E8Mxc/edit?usp=sharing) to start enumerating features that you would like for graph-plot. Please start filling out the features that you interested in [here](https://docs.google.com/document/d/1JtcYXgspLlhTsHxk8TOmZ0cFDExzGGGcA9vtAcjZS6s/edit?usp=sharing), so that I have a more formal list with clearer specifications. 

Thank you,
Henry

**Comment by cckuhlman** [comment]
Hey Henry:

I made a start.

Can you move this file under here:  https://drive.google.com/drive/folders/1ktmWcw0AnPeiONr_G4T_o4W482ML-K4y

It is now more important than ever to have these files in the project google drive, rather than your google drive.

**Comment by hcars** [comment]
@cckuhlman  and @ssravi-1984  completed this up to the point that we needed for static plotting.

**Comment by hcars** [comment]
I am pinning this, so whoever picks this up knows where to look for this document.
