### ISSUE TITLE
graph-plot using graph-trans GraphStorage objects

### ISSUE THREAD

**Issue by hcars** [NSSAC/graph-plot#3]
The Python API to [iGraph](https://igraph.org/python/doc/tutorial/tutorial.html#starting-igraph) and [GraphViz](https://pygraphviz.github.io/) would be ideal candidates for new GraphStorage objects, the abstract class structure defined for graphTrans. They provide methods I/O and graph manipulation that would fit the requirements of a GraphStorage object. Furthermore, NetworkX and Snap graph both have plotting methods. In order to utilize these plotting abilities, a new method `plotGraph(outputPath: str, plot_method: str, plot_method_args: List[str])` could be added to the GraphStorage abstract base class. This would allow us to offer multiple plotting methods for @Lucaslhm  to call via command-line, and it would allow to avoid conversions between the accepted formats of plotting tools.

@cckuhlman @ssravi-1984  What do you think?

**Comment by cckuhlman** [comment]
We'll have to talk about this.  I am not following the idea that an API would be a candidate for GraphStorage objects (api vs objects).

We can talk and see, but essentially right now, I do not prefer this.  There is one code for one objective:  to transform graphs from one format to another.  This is GraphTrans.  To put plotting in there expands the well-defined scope of the code.

This does not mean that we cannot write a companion code that does (i.e., dedicated to) graph plotting, and it might reuse some other code.  In fact, that is great.  So one code for graph transformation and one for graph plotting.  But right now---and I may not be fully appreciating what you are saying, as I stated above---I would like to keep the two goals separate, in separate codes:  transforming graphs, and plotting graphs.   The codes could then be used in combination, within a pipeline or workflow.

Another particular reason to keep the codes separate is that someone, I think it was Henry, said that we could make generating a plot of the graph a part of metadata extraction, which I very much like.

@ssravi-1984

**Comment by cckuhlman** [comment]
Let us make this a point to discuss Wednesday.  I am not following, but I'm probably just being dense.
