### ISSUE TITLE
Get a set of graphs to use in net.science for the websci demo

### ISSUE THREAD

**Issue by cckuhlman** [NSSAC/graph-plot#5]
Collect about 10 undirected graphs between 1000 and 30000 (or so) nodes.

@ssravi-1984 
@hcars

**Comment by hcars** [comment]
@cckuhlman  do you want these to belong to a particular domain application?

**Comment by cckuhlman** [comment]
I have selected about 10-12 networks, and have them cued up to run metadata extraction so that we can get number of nodes, number of edges, but rivanna is clogged right now and I do not know when they will run.

We can (hopefully) use these as the "10 networks for the first net.science" demo.

We can generate graphs on these, to see how they look.  I think the maximum graph size is like 40k nodes.

The networks are on rivanna at:  
/home/cjk8gx/fileShare/cines-initial-nets-net.science

You should be able to copy them out.

Networks list (in case you do not want to log on):

-r--r----- 1 cjk8gx users  314380 May 25 08:17 ca-hepth.giant.uel
-r--r--r-- 1 cjk8gx users 2430395 May 25 08:17 astroph.clean.giant.uel
-r--r----- 1 cjk8gx users   19236 May 25 08:17 jazz.net.clean.uel
-r--r--r-- 1 cjk8gx users  962712 May 25 08:26 wiki.uel
-rw-r----- 1 cjk8gx users 1804529 May 25 08:27 enron.giant.clean.uel
-rw-r----- 1 cjk8gx users 2042777 May 25 08:45 fb-02.trim.clean.uel
-rw-r----- 1 cjk8gx users  510945 May 25 08:45 p2p-gnutella04.uel
-rw-r----- 1 cjk8gx users  443488 May 25 08:46 sf-1.32-14.giant.uel
-r--r----- 1 cjk8gx users  356294 May 25 08:46 fhs.uel
-rw-r----- 1 cjk8gx users   91020 May 25 08:47 3218.friend.clean.uel
-rw-r----- 1 cjk8gx users  105180 May 25 08:47 3219.friend.clean.uel
-rw-r----- 1 cjk8gx users  162774 May 25 08:47 ca-grqc.giant.uel
-rw-r----- 1 cjk8gx users  428784 May 25 08:47 er1.uel


@ssravi-1984 
@hcars 
@dmachi

**Comment by hcars** [comment]
Hey all,

What is the status on this? Are we using graphs from the set that I sent @cckuhlman  yesterday?

**Comment by cckuhlman** [comment]
If all of the above networks are in the set of 89 networks that you sent yesterday, then we will not need to add these.  But if they are different, then we will add the above to your set of 89 networks.  This is because we (I) am more familiar with these and hence will use them in the demos.

Can you generate plots of these graphs?  Both plots:  nodes in graph as nodes, nodes in graph as communities?

**Comment by hcars** [comment]
> If all of the above networks are in the set of 89 networks that you sent yesterday, then we will not need to add these.
I will check this.

> Can you generate plots of these graphs? Both plots: nodes in graph as nodes, nodes in graph as communities?
Yes, I will have these for our meeting tomorrow.

**Comment by hcars** [comment]
The graphs are in .tar file called net_plots_demo.tar in the henry-small-nets-net-science/ folder. @cckuhlman

**Comment by dmachi** [comment]
I’m uploading these into the system.  Are these PNGraph or PUNGraph?

**Comment by cckuhlman** [comment]
PUNGraph
________________________________

**Comment by hcars** [comment]
Should we close this?
